name: Release Please

"on":
  push:
    branches: [ "main" ]

jobs:
  release:
    uses: blitznihar/github-actions-python-uv/.github/workflows/uv-release-please.yml@main
    with:
      package-name: "multiple-web-protocols"